### PR TITLE
test: Add etebase container to travis

### PR DESCRIPTION
**Pull request by gchaincl**

### CODE REVIEW

**Comment by tasn** [comment]
OMG, this is so cool. :heart_eyes: 
Some comments/questions:
1. What's the license of the wait-for-it script? Could we maybe add a license notice?
2. How does this work on Windows/Mac? Is docker supported there or not? Do we get these kinds of testing there too? Just wondering.
3. I guess this can easily be added to the rest of the repos, right? That's so cool!

**Comment by gchaincl** [comment]
1. This is the script I'm using: https://github.com/vishnubob/wait-for-it, license is MIT. Feel free to add the LICENCe, not sure what's the best way.
2. Not sure how this works on mac, but the current setup is travis specific.
3. We should, yes

**Comment by tasn** [comment]
1. Like in here: https://github.com/etesync/ios/blob/master/src/AboutScreen.tsx#L1
Just opened a ticket (#7) to add it to the rest of the files
2. Sure, I meant: if we ever want to test the Go library on mac/windows (on Travis), does docker work? Anyhow, I was just wondering.

**Comment by gchaincl** [comment]
1. Cool, will have a look
2. We could try

**Comment by tasn** [comment]
License for the script, should maybe be:
```
// SPDX-FileCopyrightText: © 2017  vishnubob/wait-for-it  Authors
// SPDX-License-Identifier: MIT
```

**Pull request merged**
